version: '3.6'
services:
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: 'postgres:14-alpine'
    restart: always
    ports:
      - 5532:5432
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
  web:
    build: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGPORT: 5432
      PGHOST: db
    ports:
      - 4001:4000
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  pgdata:
